{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-configuration
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
{{- end }}
