{{- include "common.values.setup" . -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "common.names.fullname" . }}-config-template
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  target:
    name: {{ template "common.names.fullname" . }}-rendered-config
    template:
      engineVersion: v2
      data:
        config.yaml: |
          {{- $config := (regexReplaceAll "({{|}})" (toYaml .Values.config) "{{ `${1}` }}" | fromYaml) -}}
          {{- $_ := set $config.appservice "as_token" `{{ .as_token }}` -}}
          {{- $_ := set $config.appservice "hs_token" `{{ .hs_token }}` -}}
          {{- $_ := set $config.bridge.provisioning "shared_secret" `{{ .provisioning_shared_secret }}` -}}
{{- with $config }}
          {{- toYaml . | nindent 10 }}
{{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: as_token
      remoteRef:
        key: matrix/appservice/mautrix-whatsapp/registration
        property: as_token
    - secretKey: hs_token
      remoteRef:
        key: matrix/appservice/mautrix-whatsapp/registration
        property: hs_token
    - secretKey: provisioning_shared_secret
      remoteRef:
        key: matrix/appservice/mautrix-whatsapp/registration
        property: provisioning_shared_secret
    - secretKey: pg_user
      remoteRef:
        key: matrix/appservice/mautrix-whatsapp/registration
        property: pg_user
    - secretKey: pg_pass
      remoteRef:
        key: matrix/appservice/mautrix-whatsapp/registration
        property: pg_pass
