{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap volume to the volumes */}}
{{- define "mx-puppet-discord.forcedEnv" -}}
CONFIG_PATH: /config/config.yaml
REGISTRATION_PATH: /config/registration.yaml
{{- end -}}
{{- $_ := set .Values "env" (merge (include "mx-puppet-discord.forcedEnv" . | fromYaml) .Values.env) -}}
{{- define "mx-puppet-discord.configVolume" -}}
enabled: "true"
mountPath: "/config"
type: "custom"
volumeSpec:
  secret:
    secretName: {{ template "common.names.fullname" . }}-rendered-config
{{- end -}}
{{- $_ := set .Values.persistence "mx-puppet-discord-config" (include "mx-puppet-discord.configVolume" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
