{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap volume to the volumes */}}
{{- define "mautrix-whatsapp.configVolume" -}}
enabled: "true"
mountPath: "/data/config.yaml"
subPath: "config.yaml"
type: "custom"
volumeSpec:
  secret:
    secretName: {{ template "common.names.fullname" . }}-rendered-config
{{- end -}}
{{- $_ := set .Values.persistence "mautrix-whatsapp-config" (include "mautrix-whatsapp.configVolume" . | fromYaml) -}}
{{- define "mautrix-whatsapp.registrationVolume" -}}
enabled: "true"
mountPath: "/data/registration.yaml"
subPath: "registration.yaml"
type: "custom"
volumeSpec:
  secret:
    secretName: {{ template "common.names.fullname" . }}-rendered-config
{{- end -}}
{{- $_ := set .Values.persistence "mautrix-whatsapp-registration" (include "mautrix-whatsapp.registrationVolume" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
